#!/bin/bash

echo "🚀 Quick Jenkins Pipeline Setup"
echo "==============================="
echo ""

echo "📋 Jenkins Access Information:"
echo "URL: http://34.228.11.74:8080"
echo "Username: admin"
echo "Password: admin123"
echo ""

echo "📝 Manual Setup Steps:"
echo "======================"
echo ""
echo "1. Go to: http://34.228.11.74:8080"
echo "2. Login with admin/admin123"
echo "3. Click 'New Item'"
echo "4. Enter job name: abc-retail-pipeline"
echo "5. Select 'Pipeline' and click OK"
echo "6. In Pipeline section, select 'Pipeline script'"
echo "7. Copy the pipeline script from jenkins-pipeline-setup-guide.md"
echo "8. Click 'Save'"
echo "9. Click 'Build Now' to run the pipeline"
echo ""

echo "🔧 Required Plugins (if not installed):"
echo "- Docker Pipeline"
echo "- Ansible"
echo "- Credentials Binding"
echo "- Git Integration"
echo ""

echo "📊 Docker Hub Credentials Setup:"
echo "1. Go to: Manage Jenkins → Credentials → System → Global credentials"
echo "2. Click 'Add Credentials'"
echo "3. Kind: Username with password"
echo "4. ID: dockerhub-creds"
echo "5. Username: vchaturvdocker"
echo "6. Password: Your Docker Hub password"
echo ""

echo "✅ Success Indicators:"
echo "- Pipeline job appears in Jenkins dashboard"
echo "- Build completes successfully"
echo "- Application accessible at: http://107.21.169.207:8080"
echo "- Monitoring available at: http://34.229.169.187:3000"
echo ""

echo "📖 For detailed instructions, see: jenkins-pipeline-setup-guide.md"
echo ""
echo "🎯 Your DevOps Pipeline will be ready once you complete these steps!" 