apiVersion: v1
kind: Service
metadata:
  name: abc-retail-service
  labels:
    app: abc-retail-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: abc-retail-app
